using MedicalWeb.BE.Transversales.Common;

namespace MedicalWeb.BE.Transversales.Core;

public class Country : EnumEntity
{
    public string Name { get; set; } = null!;

    public static IEnumerable<Country> GetAll() =>
        new List<Country>()
        {
            new Country { Id = 1, Name = "Afganistán" },
            new Country { Id = 2, Name = "Albania" },
            new Country { Id = 3, Name = "Alemania" },
            new Country { Id = 4, Name = "Andorra" },
            new Country { Id = 5, Name = "Angola" },
            new Country { Id = 6, Name = "Antigua y Barbuda" },
            new Country { Id = 7, Name = "Arabia Saudita" },
            new Country { Id = 8, Name = "Argelia" },
            new Country { Id = 9, Name = "Argentina" },
            new Country { Id = 10, Name = "Armenia" },
            new Country { Id = 11, Name = "Australia" },
            new Country { Id = 12, Name = "Austria" },
            new Country { Id = 13, Name = "Azerbaiyán" },
            new Country { Id = 14, Name = "Bahamas" },
            new Country { Id = 15, Name = "Bangladés" },
            new Country { Id = 16, Name = "Barbados" },
            new Country { Id = 17, Name = "Baréin" },
            new Country { Id = 18, Name = "Bélgica" },
            new Country { Id = 19, Name = "Belice" },
            new Country { Id = 20, Name = "Benín" },
            new Country { Id = 21, Name = "Bielorrusia" },
            new Country { Id = 22, Name = "Birmania" },
            new Country { Id = 23, Name = "Bolivia" },
            new Country { Id = 24, Name = "Bosnia y Herzegovina" },
            new Country { Id = 25, Name = "Botsuana" },
            new Country { Id = 26, Name = "Brasil" },
            new Country { Id = 27, Name = "Brunéi" },
            new Country { Id = 28, Name = "Bulgaria" },
            new Country { Id = 29, Name = "Burkina Faso" },
            new Country { Id = 30, Name = "Burundi" },
            new Country { Id = 31, Name = "Bután" },
            new Country { Id = 32, Name = "Cabo Verde" },
            new Country { Id = 33, Name = "Camboya" },
            new Country { Id = 34, Name = "Camerún" },
            new Country { Id = 35, Name = "Canadá" },
            new Country { Id = 36, Name = "Catar" },
            new Country { Id = 37, Name = "Chad" },
            new Country { Id = 38, Name = "Chile" },
            new Country { Id = 39, Name = "China" },
            new Country { Id = 40, Name = "Chipre" },
            new Country { Id = 41, Name = "Ciudad del Vaticano" },
            new Country { Id = 42, Name = "Colombia" },
            new Country { Id = 43, Name = "Comoras" },
            new Country { Id = 44, Name = "Congo" },
            new Country { Id = 45, Name = "Corea del Norte" },
            new Country { Id = 46, Name = "Corea del Sur" },
            new Country { Id = 47, Name = "Costa de Marfil" },
            new Country { Id = 48, Name = "Costa Rica" },
            new Country { Id = 49, Name = "Croacia" },
            new Country { Id = 50, Name = "Cuba" },
            new Country { Id = 51, Name = "Dinamarca" },
            new Country { Id = 52, Name = "Dominica" },
            new Country { Id = 53, Name = "Ecuador" },
            new Country { Id = 54, Name = "Egipto" },
            new Country { Id = 55, Name = "El Salvador" },
            new Country { Id = 56, Name = "Emiratos Árabes Unidos" },
            new Country { Id = 57, Name = "Eritrea" },
            new Country { Id = 58, Name = "Eslovaquia" },
            new Country { Id = 59, Name = "Eslovenia" },
            new Country { Id = 60, Name = "España" },
            new Country { Id = 61, Name = "Estados Unidos" },
            new Country { Id = 62, Name = "Estonia" },
            new Country { Id = 63, Name = "Esuatini" },
            new Country { Id = 64, Name = "Etiopía" },
            new Country { Id = 65, Name = "Filipinas" },
            new Country { Id = 66, Name = "Finlandia" },
            new Country { Id = 67, Name = "Fiyi" },
            new Country { Id = 68, Name = "Francia" },
            new Country { Id = 69, Name = "Gabón" },
            new Country { Id = 70, Name = "Gambia" },
            new Country { Id = 71, Name = "Georgia" },
            new Country { Id = 72, Name = "Ghana" },
            new Country { Id = 73, Name = "Granada" },
            new Country { Id = 74, Name = "Grecia" },
            new Country { Id = 75, Name = "Guatemala" },
            new Country { Id = 76, Name = "Guinea" },
            new Country { Id = 77, Name = "Guinea-Bisáu" },
            new Country { Id = 78, Name = "Guinea Ecuatorial" },
            new Country { Id = 79, Name = "Guyana" },
            new Country { Id = 80, Name = "Haití" },
            new Country { Id = 81, Name = "Honduras" },
            new Country { Id = 82, Name = "Hungría" },
            new Country { Id = 83, Name = "India" },
            new Country { Id = 84, Name = "Indonesia" },
            new Country { Id = 85, Name = "Irak" },
            new Country { Id = 86, Name = "Irán" },
            new Country { Id = 87, Name = "Irlanda" },
            new Country { Id = 88, Name = "Islandia" },
            new Country { Id = 89, Name = "Islas Marshall" },
            new Country { Id = 90, Name = "Islas Salomón" },
            new Country { Id = 91, Name = "Israel" },
            new Country { Id = 92, Name = "Italia" },
            new Country { Id = 93, Name = "Jamaica" },
            new Country { Id = 94, Name = "Japón" },
            new Country { Id = 95, Name = "Jordania" },
            new Country { Id = 96, Name = "Kazajistán" },
            new Country { Id = 97, Name = "Kenia" },
            new Country { Id = 98, Name = "Kirguistán" },
            new Country { Id = 99, Name = "Kiribati" },
            new Country { Id = 100, Name = "Kuwait" },
            new Country { Id = 101, Name = "Laos" },
            new Country { Id = 102, Name = "Lesoto" },
            new Country { Id = 103, Name = "Letonia" },
            new Country { Id = 104, Name = "Líbano" },
            new Country { Id = 105, Name = "Liberia" },
            new Country { Id = 106, Name = "Libia" },
            new Country { Id = 107, Name = "Liechtenstein" },
            new Country { Id = 108, Name = "Lituania" },
            new Country { Id = 109, Name = "Luxemburgo" },
            new Country { Id = 110, Name = "Madagascar" },
            new Country { Id = 111, Name = "Malasia" },
            new Country { Id = 112, Name = "Malaui" },
            new Country { Id = 113, Name = "Maldivas" },
            new Country { Id = 114, Name = "Malí" },
            new Country { Id = 115, Name = "Malta" },
            new Country { Id = 116, Name = "Marruecos" },
            new Country { Id = 117, Name = "Mauricio" },
            new Country { Id = 118, Name = "Mauritania" },
            new Country { Id = 119, Name = "México" },
            new Country { Id = 120, Name = "Micronesia" },
            new Country { Id = 121, Name = "Moldavia" },
            new Country { Id = 122, Name = "Mónaco" },
            new Country { Id = 123, Name = "Mongolia" },
            new Country { Id = 124, Name = "Montenegro" },
            new Country { Id = 125, Name = "Mozambique" },
            new Country { Id = 126, Name = "Namibia" },
            new Country { Id = 127, Name = "Nauru" },
            new Country { Id = 128, Name = "Nepal" },
            new Country { Id = 129, Name = "Nicaragua" },
            new Country { Id = 130, Name = "Níger" },
            new Country { Id = 131, Name = "Nigeria" },
            new Country { Id = 132, Name = "Noruega" },
            new Country { Id = 133, Name = "Nueva Zelanda" },
            new Country { Id = 134, Name = "Omán" },
            new Country { Id = 135, Name = "Países Bajos" },
            new Country { Id = 136, Name = "Pakistán" },
            new Country { Id = 137, Name = "Palaos" },
            new Country { Id = 138, Name = "Panamá" },
            new Country { Id = 139, Name = "Papúa Nueva Guinea" },
            new Country { Id = 140, Name = "Paraguay" },
            new Country { Id = 141, Name = "Perú" },
            new Country { Id = 142, Name = "Polonia" },
            new Country { Id = 143, Name = "Portugal" },
            new Country { Id = 144, Name = "Reino Unido" },
            new Country { Id = 145, Name = "República Centroafricana" },
            new Country { Id = 146, Name = "República Checa" },
            new Country { Id = 147, Name = "República Democrática del Congo" },
            new Country { Id = 148, Name = "República Dominicana" },
            new Country { Id = 149, Name = "Ruanda" },
            new Country { Id = 150, Name = "Rumania" },
            new Country { Id = 151, Name = "Rusia" },
            new Country { Id = 152, Name = "Samoa" },
            new Country { Id = 153, Name = "San Cristóbal y Nieves" },
            new Country { Id = 154, Name = "San Marino" },
            new Country { Id = 155, Name = "San Vicente y las Granadinas" },
            new Country { Id = 156, Name = "Santa Lucía" },
            new Country { Id = 157, Name = "Santo Tomé y Príncipe" },
            new Country { Id = 158, Name = "Senegal" },
            new Country { Id = 159, Name = "Serbia" },
            new Country { Id = 160, Name = "Seychelles" },
            new Country { Id = 161, Name = "Sierra Leona" },
            new Country { Id = 162, Name = "Singapur" },
            new Country { Id = 163, Name = "Siria" },
            new Country { Id = 164, Name = "Somalia" },
            new Country { Id = 165, Name = "Sri Lanka" },
            new Country { Id = 166, Name = "Suazilandia" },
            new Country { Id = 167, Name = "Sudáfrica" },
            new Country { Id = 168, Name = "Sudán" },
            new Country { Id = 169, Name = "Sudán del Sur" },
            new Country { Id = 170, Name = "Suecia" },
            new Country { Id = 171, Name = "Suiza" },
            new Country { Id = 172, Name = "Surinam" },
            new Country { Id = 173, Name = "Tailandia" },
            new Country { Id = 174, Name = "Tanzania" },
            new Country { Id = 175, Name = "Tayikistán" },
            new Country { Id = 176, Name = "Timor Oriental" },
            new Country { Id = 177, Name = "Togo" },
            new Country { Id = 178, Name = "Tonga" },
            new Country { Id = 179, Name = "Trinidad y Tobago" },
            new Country { Id = 180, Name = "Túnez" },
            new Country { Id = 181, Name = "Turkmenistán" },
            new Country { Id = 182, Name = "Turquía" },
            new Country { Id = 183, Name = "Tuvalu" },
            new Country { Id = 184, Name = "Ucrania" },
            new Country { Id = 185, Name = "Uganda" },
            new Country { Id = 186, Name = "Uruguay" },
            new Country { Id = 187, Name = "Uzbekistán" },
            new Country { Id = 188, Name = "Vanuatu" },
            new Country { Id = 189, Name = "Venezuela" },
            new Country { Id = 190, Name = "Vietnam" },
            new Country { Id = 191, Name = "Yemen" },
            new Country { Id = 192, Name = "Yibuti" },
            new Country { Id = 193, Name = "Zambia" },
            new Country { Id = 194, Name = "Zimbabue" }
        };
}